# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6eab937e1e5ad7060ed24438c7e1a302a39a50450c432922431267137767e84e41fecd7aa1945227b3d24d4519f7d0693ba7afd591271904922d33adbc93222

test:
  secret_key_base: 56b6c044bfcdf5a5046fb0d6bae5573142cc124ea00339ea2391e608a414aae56586af82b4f86f8c96af2a24d40fb366584946d12b16e0ef7ec260dd2c9e8a11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
